### ISSUE TITLE
Add CodeSnippet plugin to ckeditor4-react ?

### ISSUE THREAD

**Issue by RealSlimMahdi** [ckeditor/ckeditor4-react#102]
Hello,

I am using ckeditor4-react 1.1.0
I cannot achieve to install extra plugin, for instance CodeSnippet.
Is there a simple way to achieve this ?

Thanks

**Comment by jacekbogdanski** [comment]
Please, read documentation on how to [Change editor configuration](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_react.html#changing-the-editor-configuration) in React integration.
