### ISSUE TITLE
on load ckeditor in reactjs first time data not uploaded in edit form

### ISSUE THREAD

**Issue by chandra-prakash-soni** [ckeditor/ckeditor4-react#106]
on load ckeditor in reactjs first time data not uploaded in edit form

**Comment by jacekbogdanski** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.

**Comment by chandra-prakash-soni** [comment]
Here is my code. 

import CKEditor from 'ckeditor4-react';
import ClassicEditor from "@ckeditor/ckeditor5-build-classic";


// Componenent 

renderEditor1({input}) {
        return (
          <CKEditor
            data={input.value}
            editor={ ClassicEditor }
            config={{ckfinder: {
              uploadUrl: API_PATHS.IMAGE_UPLOAD,
            },filebrowserUploadUrl:  API_PATHS.IMAGE_UPLOAD  }}
            onInit={ editor => {
                console.log( 'Editor is ready to use!', editor );
            } }
            onChange={(event) => {
                return input.onChange(event.editor.getData())
              }
            }
          />
        )
      }


<Field name="topicText" component={this.renderEditor1}  placeholder="Description"   />
