### ISSUE TITLE
video

### ISSUE THREAD

**Issue by diliptarkhala** [ckeditor/ckeditor4-react#108]
## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* Integration version: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
Closing as no information on the issue was provided.
