### ISSUE TITLE
onError callback is absent to customize showing the error message in the broswer incase of failed imageuploads

### ISSUE THREAD

**Issue by chandanreddyreguri** [ckeditor/ckeditor4-react#115]
## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: … chrome
* OS: … windows
* Integration version: …
* CKEditor version: …  "ckeditor4-react": "^1.0.1",
* Installed CKEditor plugins: … filebrowserUploadUrl

**Comment by Dumluregn** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.
