### ISSUE TITLE
The install instructions in @wiris/mathtype-ckeditor4 is not working for ckeditor4-react basic CRA app

### ISSUE THREAD

**Issue by henok-tesfaye** [ckeditor/ckeditor4-react#118]
## Are you reporting a feature request or a bug?
Bug

https://www.npmjs.com/package/@wiris/mathtype-ckeditor4#install-instructions I just followed the instructions here to add Mathtype to ckeditor4-react, but editor won't load.

Note this is working with `ckeditor4` instead of `ckeditor4-react`.

```
<body>
	<div id="editor">Hello!</div>
	<script src="./node_modules/ckeditor4/ckeditor.js"></script>
	<script>
		CKEDITOR.plugins.addExternal( 'ckeditor_wiris', '../../node_modules/@wiris/mathtype-ckeditor4/plugin.js' );

		CKEDITOR.replace( 'editor', {
			extraPlugins: 'ckeditor_wiris'
		} );
	</script>
</body>
```

## Provide detailed reproduction steps (if any)

1. Open https://codesandbox.io/s/silly-thunder-v7pkl?file=/src/App.js simple CRA.

```import React, { Component } from "react";
import CKEditor from "ckeditor4-react";

class App extends Component {
  render() {
    return (
      <div className="App">
        <h2>Using CKEditor 4 in React</h2>
        <CKEditor
          data="<p>Hello from CKEditor 4!</p>"
          config={{
            extraPlugins: "ckeditor_wiris",
            // Allow MathML content.
            allowedContent: true
          }}
          onBeforeLoad={(CKEDITOR) => {
            CKEDITOR.plugins.addExternal(
              "ckeditor_wiris",
              "../node_modules/@wiris/mathtype-ckeditor4/",
              "plugin.js"
            );
          }}
        />
      </div>
    );
  }
}

export default App;
```

2. Check if editor is proper displayed

### Expected result

*What is the expected result of the above steps?*
Editor with Mathtype plugin should be displayed 
### Actual result
Editor is not displayed
*What is the actual result of the above steps?*

## Other details

* Browser: Version 85.0.4183.83 (Official Build) (64-bit)
* OS: OSX
* Integration version: 
* CKEditor version: latest (`npm install ckeditor4-react`)
* Installed CKEditor plugins: https://www.npmjs.com/package/@wiris/mathtype-ckeditor4

**Comment by f1ames** [comment]
@henok-tesfaye please take a look on https://github.com/ckeditor/ckeditor4-react/issues/117#issuecomment-687076063.
