### ISSUE TITLE
Refresh the integration

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4-react#123]
## Are you reporting a feature request or a bug?

Task

## Provide details

Currently our Rect integration is much different than the rest of our integrations. We should polish it a bit:

* [ ] Add proper `npm start` script.
* [ ] Ensure that samples are published alongside the package.
* [ ] Make samples more complex to really show what the integration can do.

**Comment by sculpt0r** [comment]
I would add `travis.yml` update to this list. The same as common integrations use (with `os` and without `sudo`)

**Comment by f1ames** [comment]
Fixed in `2.0.0` version (https://github.com/ckeditor/ckeditor4-react/commit/f03dde821f2d5b62d46c4a2e80345aae2d7f39f0 and https://www.npmjs.com/package/ckeditor4-react/v/2.0.0).
