### ISSUE TITLE
Bump script doesn't update tests CDN editor version

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4-react#137]
## Are you reporting a feature request or a bug?

Task

## Provide detailed reproduction steps (if any)

It seems test have it's own `editorUrl` defined - https://github.com/ckeditor/ckeditor4-react/blob/710c2ae0b1c522d6ba517072acc546ab623ec81a/tests/browser/ckeditor.jsx#L22

Which is not updated by [bump script](https://github.com/ckeditor/ckeditor4-react/blob/master/scripts/bump.js). Not sure why it's even there so we should get rid of redefining `editorUrl` in tests so the component default editor URL will be used. And if there is any particular reason it should be there, then bump script should also update it.

**Comment by MMMalik** [comment]
This task is not relevant anymore. Neither for v1 nor for v2.
