### ISSUE TITLE
When I undo I will get following error and undo redo not work then.

### ISSUE THREAD

**Issue by abhijitkc** [ckeditor/ckeditor4-react#138]
![Screenshot from 2020-10-13 01:29:56](https://user-images.githubusercontent.com/36158867/95785819-1cd1d800-0cf4-11eb-9396-78bd8228b3b9.png)
Bug

## Other details

* Browser: … Chrome
* CKEditor version: … 4

**Comment by f1ames** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor4-react/issues/new). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
