### ISSUE TITLE
How can I use my local js file?

### ISSUE THREAD

**Issue by Wislove** [ckeditor/ckeditor4-react#14]
I use react create my app, but it load very slow

in ckeditor.js has one line code
 `CKEditor.editorUrl = 'https://cdn.ckeditor.com/4.11.1/standard-all/ckeditor.js';`

how can I replace the url with my local js file?

**Comment by Zemelia** [comment]
@Wislove 

Hi, like this:

```
import CKEditor from 'ckeditor4-react';

CKEditor.editorUrl = '<your local url>';
```

**Comment by Comandeer** [comment]
Thanks for answering this question, @Zemelia! That's the easiest way to do it.

**Comment by codeforsure** [comment]
can I know with relative to what I should give the path
