### ISSUE TITLE
Facing uncaught type-error on production environment. 

### ISSUE THREAD

**Issue by Divisha-joshi** [ckeditor/ckeditor4-react#167]
CKEditor4-react version - 1.4.0, giving uncaught type-error on the production environment.
Tried to use npm i --save-dev @types/ckeditor4-react and got this as an error - '@types/ckeditor4-react@latest' is not in the npm registry.'

**Comment by sculpt0r** [comment]
Hi @Divisha-joshi ,

We don't provide types, since this integration is not strict for typescript, but could be used with it.

Also, we already have a report for typescript support: #82. I hope it will be helpful.  
  
Since your report is not actually a bug, I close this issue.
