### ISSUE TITLE
Installing plugins

### ISSUE THREAD

**Issue by sergeycw** [ckeditor/ckeditor4-react#17]
Hi! Is there any guide about how to work with CKEditor plugins in react?

**Comment by Comandeer** [comment]
No, there isn't any official guide. The CKEditor 4 React component assumes that CKEditor is loaded before creating any `CKeditor` components. This way you can pass it [URL to custom build of CKEditor](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_react.html#customizing-ckeditor-preset-or-version) with every needed plugin:

```javascript
CKEditor.editorUrl = 'https://your-website.example/ckeditor/ckeditor.js';
```

To load plugins into the editor's instance, [pass `config` prop to the component](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_react.html#changing-editor-configuration):

```javascript
<CKEditor
    config={ {
        extraPlugins: 'extra,plugins'
    } }
/>
```

**Comment by codeforsure** [comment]
Hi, I was trying to use local ckeditor file downloaded with custom plugins. I am trying to use

`CKEditor.editorUrl ='⁨/Users⁩/⁨name/⁨Desktop/ckeditor/ckeditor.js⁩';`
but I can't render ckeditor component

**Comment by Comandeer** [comment]
@codeforsure, using absolute filesystem path do not work in web applications. It's better to use path relative to the application's directory.

**Comment by codeforsure** [comment]
Hi @Comandeer ,By application you mean relative to react app directory

**Comment by slam24** [comment]
Hi @Comandeer, add your code lines but don't load the plugin.

`import CKEditor from 'ckeditor4-react';`
`CKEditor.editorUrl = '../../public/bower_components/ckeditor/ckeditor.js';`
`                <CKEditor
                  data="<p>This is an example CKEditor 4 instance.</p>"
                  config={ {
                    extraPlugins: 'docprops'
                  } }
                />`

**Comment by Comandeer** [comment]
I'm closing this issue for now. If there are some concerns about the quality of [React integration docs](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_react.html), please open a new issue.

**Comment by yanlee26** [comment]
> @codeforsure, using absolute filesystem path do not work in web applications. It's better to use path relative to the application's directory.

Not work yet.
