### ISSUE TITLE
Provide webpack 5 config for karma-webpack

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4-react#172]
## Are you reporting a feature request or a bug?

Task

## Details

`karma-webpack 5.0.0` with Webpack 5 support is out. However we need to provide a custom config to make it work - otherwise testing environment is not created correctly.

**Comment by MMMalik** [comment]
I believe that this task is not relevant anymore and it can be closed. v2 version of `ckeditor4-react` is using Rollup rather than Webpack to produce library outputs.
