### ISSUE TITLE
license statement in package metadata misleading/incomplete

### ISSUE THREAD

**Issue by jamin-aws-ospo** [ckeditor/ckeditor4-react#181]
## Type of report

Task

## Provide description of the task

The [licensing information listed in the package metadata](https://github.com/ckeditor/ckeditor4-react/blob/master/package.json#L5) states:
```
"license": "(GPL-2.0-or-later OR LGPL-2.1 OR MPL-1.1)"
```

However, the [LICENSE.md](https://github.com/ckeditor/ckeditor4-react/blob/master/LICENSE.md) indicates:
```
GNU General Public License Version 2 or later (the "GPL") http://www.gnu.org/licenses/gpl.html

GNU Lesser General Public License Version 2.1 or later (the "LGPL") http://www.gnu.org/licenses/lgpl.html

Mozilla Public License Version 1.1 or later (the "MPL") http://www.mozilla.org/MPL/MPL-1.1.html
```

Note the **or later** on each of the licenses.

The above should not be taken as an exhaustive list, it's just what I found by spot checking.

*What steps should be taken to fulfil the task?*
Correct/clarify the licensing terms of the project/package.

## Other details
N/A

**Comment by sculpt0r** [comment]
Hi @jamin-aws-ospo ,

Thank you for the report. I can confirm this.

**Comment by jacekbogdanski** [comment]
@jamin-aws-ospo thanks for letting us know. I've updated `package.json` file in https://github.com/ckeditor/ckeditor4-react/commit/3119c915200616b005d880582d448a2bb2f438e9
This change will be available in the next CKEditor 4 React integration release.
