### ISSUE TITLE
Verify conditions (nodeJS version) to run Ultimate React Tester

### ISSUE THREAD

**Issue by sculpt0r** [ckeditor/ckeditor4-react#190]
## Are you reporting a feature request or a bug?

Task

## Provide detailed reproduction steps (if any)

1. Make sure you have an **invalid** nodeJS version (e.g. 10 / 12)
2. Run `npm run test:all-versions`

### Expected result

Console produces logs about invalid nodeJS environment version.

### Actual result

There is only `undefined` and crashed npm in the console.
![image](https://user-images.githubusercontent.com/6498567/114002167-ec12cb80-985c-11eb-8dcb-13f6bee6e937.png)

## Other details
We could just add information about the proper nodeJS version to README. Besides that, we can add some verification and produce a proper log.

* Browser: -
* OS: Ubuntu 20.04
* Integration version: 1.4.0
* CKEditor version: 4.16.0
* Installed CKEditor plugins: -

**Comment by MMMalik** [comment]
We already have `.nvmrc` file in the project's root. Running `nvm use` should get you the correct version. Maybe that's enough? WDYT?

**Comment by sculpt0r** [comment]
> We already have `.nvmrc` file in the project's root. Running `nvm use` should get you the correct version. Maybe that's enough? WDYT?

Yeah, I think it will be enough
