### ISSUE TITLE
toolbar not full functions

### ISSUE THREAD

**Issue by nguyenvanphuc2203** [ckeditor/ckeditor4-react#20]
how to config toolbar full function like this
![image](https://user-images.githubusercontent.com/33291479/53633330-bfd1fd00-3c49-11e9-8495-f6924d77dc8e.png)
here my editor :
![screen shot 2019-03-01 at 5 45 52 pm](https://user-images.githubusercontent.com/33291479/53633396-ec861480-3c49-11e9-97ff-874d0cbea07b.png)

**Comment by Comandeer** [comment]
The easiest way would be to [customise editor's preset](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_react.html#customizing-ckeditor-preset-or-version).
