### ISSUE TITLE
1.5.0 release

### ISSUE THREAD

**Issue by shir** [ckeditor/ckeditor4-react#200]
Please release 1.5.0. It has an important fix but is not released for a while. And in the Changelog file it looks like released but I don't see the version in the npm repository.

**Comment by f1ames** [comment]
Hello @shir, you are right, `1.5.0` is not published yet.

Let me check what we have in the pipeline and if `1.5.0` can be safety released now, I'll get back to you soon :+1:

**Comment by f1ames** [comment]
Hi @shir,

The new version is `1.4.1` since it contains only bug fixes (so `patch` update). The `1.5.0` was a typo on our end.

Anyway, new version it's already on NPM (https://www.npmjs.com/package/ckeditor4-react/v/1.4.1) :tada: :+1:

**Comment by shir** [comment]
@f1ames thank you!
