### ISSUE TITLE
Use `delayIfDetached` config for editor set to `true` by default.

### ISSUE THREAD

**Issue by sculpt0r** [ckeditor/ckeditor4-react#203]
## Are you reporting a feature request or a bug?
Task.

Base on our investigation on https://github.com/ckeditor/ckeditor4/issues/4390 issue and fix we provide for it: https://github.com/ckeditor/ckeditor4/pull/4463. We should use the `delayIfDetached` config set to `true` by default in integrations, just to prevent any issue. Also, we need to adjust editor creation: to properly maintain editor data https://github.com/ckeditor/ckeditor4-react/blob/371c23daa2445d17ef41dbceb2142b648e400530/src/ckeditor.jsx#L75 The above line assumes we get editor instance, but that doesn't have to be true with delayed creation.

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: -
* OS: -
* Integration version: -
* CKEditor version: -
* Installed CKEditor plugins: -

**Comment by sculpt0r** [comment]
Blocked until `4.17.0` release.

**Comment by sculpt0r** [comment]
@MMMalik - Am I good remember that we talked, that this issue could be closed due to nature of component creation in react? If so - we may close it 👾

**Comment by MMMalik** [comment]
I tested nightly build of `ckeditor` with both v1 and v2 `ckeditor4-react` and I haven't spotted any issues. I think we close this task for now.
