### ISSUE TITLE
Getting error "cannot read property setReadOnly of undefined"

### ISSUE THREAD

**Issue by Sugao1995** [ckeditor/ckeditor4-react#210]
## Provide detailed reproduction steps (if any)
Kind of inconsistent 

1. make sure editor is being passed a readOnly property that can be changed by another component
2. open the text editor

### Expected result

Expected for Text editor to appear with no errors.

### Actual result

Got error stating "cannot read property setReadOnly of undefined".

## Other details

Debugging through ckeditor and ckeditor-react, I see that the error is being thrown from editor.js in ckeditor4/core/. It seems like ckeditor-react is calling setReadOnly in its componentDidUpdate method before the editor is ready. 

* Browser: Chrome
* OS: Windows 10
* Integration version: 1.4.1
* CKEditor version: 4.16
* Installed CKEditor plugins: ckeditor4-integrations-common 0.2.0

**Comment by Comandeer** [comment]
Can you provide some example?
