### ISSUE TITLE
Bug each time the event emit , one new instance will be created

### ISSUE THREAD

**Issue by yanlee26** [ckeditor/ckeditor4-react#211]
## Provide detailed reproduction steps 

1. cke_editor3 
2. cke_editor4
3. …

every time when the event was emitted, the new instance of ckeditor will be created, which makes the UI jump and the UED very bad

**Comment by f1ames** [comment]
Hi @yanlee26, could you provide more detailed description and reproduction steps (or a codepen sample) for your issue?
