### ISSUE TITLE
CONTRIBUTING.md leads to invalid URL for NPM package in v2

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4-react#220]
## Are you reporting a feature request or a bug?

Task

## Provide detailed reproduction steps (if any)

The Contributing section was a part of the `README.md` file in v1:

* How it looks on NPM https://www.npmjs.com/package/ckeditor4-react/v/1.4.2#contributing.

And for v2 it is a separate file. This is fine, however for published package, invalid link is generated, see https://www.npmjs.com/package/ckeditor4-react#contributing, which leads to non-existing resource `https://github.com/ckeditor/ckeditor4-react/blob/HEAD/CONTRIBUTING.md`.

We could either move it to `README.md` or add some build step which will inline it during build/publication or fix the link :thinking:

**Comment by MMMalik** [comment]
The link should work fine once the CONTRIBUTING lands in the `master` branch, so I'm not sure if it's worth fixing it.

**Comment by f1ames** [comment]
> The link should work fine once the CONTRIBUTING lands in the `master` branch, so I'm not sure if it's worth fixing it.

Ok, makes sense, so once RC version becomes stable, it will work just fine :+1:

**Comment by MMMalik** [comment]
Or should we use `stable` branch in such links? 🤔

**Comment by f1ames** [comment]
> Or should we use `stable` branch in such links?

There can be some unpublished changes on `master` so `stable` would make sense :+1: OTOH, if one wants to contribute, he/she needs most recent "instructions" which will be on `master` :thinking: 

Still, not sure if those files will change that often, so maybe let's go with `stable`?

**Comment by MMMalik** [comment]
Okay, so the link is relative to the current branch:

```
See [CONTRIBUTING.md](CONTRIBUTING.md)
```

It will point to `CONTRIBUTING` on `major` if you're on `major` branch, to `master` if you're on `master`, etc. This works only on GitHub though. From npmjs.com it will point to default branch from what I can see.

Honestly, I'd keep it as it is. Maybe we can close this issue?

**Comment by f1ames** [comment]
Will be solved together with #229.

**Comment by f1ames** [comment]
Fixed in `2.0.0` version (https://github.com/ckeditor/ckeditor4-react/commit/f03dde821f2d5b62d46c4a2e80345aae2d7f39f0 and https://www.npmjs.com/package/ckeditor4-react/v/2.0.0).
