### ISSUE TITLE
Update LICENSE file

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4-react#23]
Currently the license contain information only about our integration, without further information about used components and libraries.

**Comment by f1ames** [comment]
It was already done in Angular integration, see its [LICENSE.md file](https://github.com/ckeditor/ckeditor4-angular/blob/fa7287b50d868933e76cdf936e9c7e03947f607f/LICENSE.md#sources-of-intellectual-property-included-in-ckeditor).
