### ISSUE TITLE
TypeError: b.getEditor is not a function

### ISSUE THREAD

**Issue by Egor-Lee** [ckeditor/ckeditor4-react#239]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

Sorry I'm not able to provide the environment.
All I do is the basic usage:

import { CKEditor } from 'ckeditor4-react';
&lt;CKEditor initData={content} readOnly={true} /&gt;

### Expected result

Hmmm... I'm sure we all know what should be here. 

### Actual result

![image](https://user-images.githubusercontent.com/42730042/127270919-6b3137ab-5283-430d-975f-6c0575f28472.png)
And the tag CKEditor renders just nothing.

## Other details

* Browser: Chrome 92.0.4515.107 (64 bit)
* OS: Windows 10 professional
* Integration version: ckeditor4-react 2.0.0
* CKEditor version: unknown
* Installed CKEditor plugins: no
* Node version: 14.17.3
* React version: 16.14.0

**Comment by sculpt0r** [comment]
Hi @Egor-Lee 
Thank you for moving with the issue to this repo 👍 

I'm trying to reproduce this issue and I can't...

I tried with CRA and on stackblitz default react template, our [sample code](https://stackblitz.com/edit/ckeditor4-react-bug-report), and still no errors.

Could you provide some zipped project, GH repo, modified https://stackblitz.com/edit/ckeditor4-react-bug-report project with this bug? What steps did you make to set up the project? Anything more could be helpfull.

**Comment by Egor-Lee** [comment]
Hi there,

Everything works fine on StackBlitz.
I noticed there is a dependency on ckeditor4@4.16.1.
I ran 'npm i --save ckeditor4' on my workspace, but the issue remains intact.
Is there any chance I run some procedure and offer debugging information to proceed?

**Comment by sculpt0r** [comment]
Hi,
If you take a look into peer dependencies: https://github.com/ckeditor/ckeditor4-react/blob/3d0c33be508dd3fc81f771fa283e32042b487c5a/package.json#L53-L56

There is ckeditor4 in the list. This is kind of obvious, but now I see there is react `16.9` or `17` and you are using `16.14.0` 🤔  can your try to bump react in your project?

**Comment by Egor-Lee** [comment]
Sorry, my project is not allowed to upgrade React 17.
I'll close this issue and try other solutions, thank you anyway.

**Comment by sculpt0r** [comment]
Hi @Egor-Lee 
You can always try to use `16.9` or our late v1 version: https://github.com/ckeditor/ckeditor4-react/releases/tag/v1.4.2

Just to check where is the problem.
