### ISSUE TITLE
Editor-plugin-conflict

### ISSUE THREAD

**Issue by kristian2x** [ckeditor/ckeditor4-react#24]
I am having a problem with setting up image upload with ckeditor4-react.  I have this config set up:

```
config={{
  extraPlugins: 'image2,uploadimage',
  imageUploadUrl: "/api/mailing/" + this.props.mailingId + "/upload_editor_image",
  uploadUrl: "/api/mailing/" + this.props.mailingId + "/upload_editor_image",
  filebrowserUploadUrl: "/api/mailing/" + this.props.mailingId + "/upload_editor_image",
  filebrowserImageUploadUrl: "/api/mailing/" + this.props.mailingId + "/upload_editor_image"
}}
```

The error I am getting is: 

> [CKEDITOR] Error code: editor-plugin-conflict. {plugin: "image", replacedWith: "image2"}

How can I tell CKEditor to just load image2 instead of image?

**Comment by f1ames** [comment]
Hello @kristian2x,
you could use custom editor build (see [Customizing CKEditor preset or version](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_react.html#customizing-ckeditor-preset-or-version) on React docs) with `image2` plugin only (custom build could be created with [online builder](https://ckeditor.com/ckeditor-4/download/)) or just remove `image` plugin with [`removePlugins`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-removePlugins) config.

By the way, the error you mentioned means that `image2` plugin was loaded instead of `image`, see [editor-plugin-conflict error docs](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_errors.html#editor-plugin-conflict).

**Comment by kristian2x** [comment]
Thank you @f1ames !

**Comment by wenisy** [comment]
> I am having a problem with setting up image upload with ckeditor4-react. I have this config set up:
> 
> ```
> config={{
>   extraPlugins: 'image2,uploadimage',
>   imageUploadUrl: "/api/mailing/" + this.props.mailingId + "/upload_editor_image",
>   uploadUrl: "/api/mailing/" + this.props.mailingId + "/upload_editor_image",
>   filebrowserUploadUrl: "/api/mailing/" + this.props.mailingId + "/upload_editor_image",
>   filebrowserImageUploadUrl: "/api/mailing/" + this.props.mailingId + "/upload_editor_image"
> }}
> ```
> 
> The error I am getting is:
> 
> > [CKEDITOR] Error code: editor-plugin-conflict. {plugin: "image", replacedWith: "image2"}
> 
> How can I tell CKEditor to just load image2 instead of image?

Hi, how could you use extraPlugins?

I use https://ckeditor.com/cke4/builder builder to download a folder, there are lots of files, should I only use `ckeditor.js` ?

**Comment by f1ames** [comment]
Hi @wenisy,
If you are using the online builder (https://ckeditor.com/cke4/builder) you should create a build which includes all required plugins so there is no need to use `extraPlugins`. You can do this in the second step of a builder:

![image](https://user-images.githubusercontent.com/1061942/61204522-acea3180-a6ed-11e9-888b-0d03a24c671f.png)

If you still need to use `extraPlugins` the first https://github.com/ckeditor/ckeditor4-react/issues/24#issue-424810302 from this thread shows how it should be done.

---

To include editor build you just need to [include `ckeditor.js` file](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_installation.html#adding-ckeditor-to-your-page) or if you have and bundling step it might be included there too.

**Comment by wenisy** [comment]
@f1ames Thanks!
So only `ckeditor.js` is enough? No more plugin js from other folder?


for this `dropdownmenumanager` plugin, if I want to use it as my extraPlugins, how shoud I do?

is this fine?

![image](https://user-images.githubusercontent.com/5832130/61206753-eb9bde00-a725-11e9-99bf-851be7c7ada8.png)

**Comment by wenisy** [comment]
I might figure it out now.


change the code like this

![image](https://user-images.githubusercontent.com/5832130/61210550-687f8580-a72f-11e9-951b-7f1579dcea56.png)

`editorConfig.toolbar.push({ name: 'widgets', items: ['Widgets'] })` not `editorConfig.toolbar.push('Widgets')`
