### ISSUE TITLE
Adjust information about React support in React v1 docs

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4-react#240]
## Are you reporting a feature request or a bug?

Task

## Provide detailed reproduction steps (if any)

As stated on the beginning of [v1 guides](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_react_v1.html):

> CKEditor 4 offers a native React integration through the CKEditor 4 React component. It provides deep integration of CKEditor 4 and React that lets you use the native features of the WYSIWYG editor inside a React component. The CKEditor 4 React component is compatible with React versions higher than v16.0.x but lower than v17.x. Although it seems to be working with React v17.x, we do not provide any support in that regard.

I think it will be good to adjust (or even remove) this section since it might be misleading.

**Comment by jacekbogdanski** [comment]
Let's add a statement if you would like to use React 17 you should use 2.x.x. integration version.
