### ISSUE TITLE
It's Unclear How To Start With *HTML* (Not JSX) In the Editor

### ISSUE THREAD

**Issue by machineghost** [ckeditor/ckeditor4-react#264]
## Are you reporting a feature request or a bug?

Documentation bug.

## Provide detailed reproduction steps (if any)

1. Read the documentation.
2. Try to figure out how to start with HTML (eg. from a database) in the editor instead of hard-coded JSX.
3. Fail to do so.

### Expected result

And HTML editor should be able to explain how to start with HTML in it.

### Actual result

No explanation.

**Comment by MMMalik** [comment]
That's a valid point. We'll improve the docs.

In the meantime, I'll just mention that it's of course possible to supply either JSX or string with HTML markup as `initData` prop. See [basic sample](https://github.com/ckeditor/ckeditor4-react/blob/master/samples/basic/src/App.jsx).

**Comment by machineghost** [comment]
Thanks!

**Comment by MMMalik** [comment]
Closed by ckeditor/ckeditor4-docs#406
