### ISSUE TITLE
Resource not found when adding `lineheight` in extraPlugins

### ISSUE THREAD

**Issue by henok-outlier** [ckeditor/ckeditor4-react#273]
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)
https://codesandbox.io/s/ckeditor4-react-bug-report-forked-tesud?file=/src/App.js

CKEditor is not loading when adding `lineheight` plugin. Following the guide here on how to add plugins(https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-extraPlugins)

1. …
2. …
3. …

### Expected result
A line height option should show up in the editor similar to font size

*What is the expected result of the above steps?*

### Actual result
```
ckeditor.js:97 GET https://cdn.ckeditor.com/4.14.0/full-all/plugins/lineheight/plugin.js?t=K24B net::ERR_ABORTED 404
...
ckeditor.js:257 Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "lineheight" was not found at "https://cdn.ckeditor.com/4.14.0/full-all/plugins/lineheight/plugin.js?t=K24B".
    at CKEDITOR.resourceManager.<anonymous> (ckeditor.js:257:196)
    at f (ckeditor.js:252:379)
    at Array.n (ckeditor.js:253:1)
    at q (ckeditor.js:253:85)
    at HTMLScriptElement.CKEDITOR.env.ie.d.$.onerror (ckeditor.js:254:92)
```
*What is the actual result of the above steps?*

## Other details

* Browser: Chrome Version 97.0.4692.71 (Official Build) (x86_64)
* OS: OSX
* Integration version: 4.14.0
* CKEditor version: 1
* Installed CKEditor plugins: lineheight

**Comment by henok-outlier** [comment]
It's because `lineheight` plugin is not served from the CDN, so we should add the plugin(https://ckeditor.com/cke4/addon/lineheight) to the `extraPlugins` with the static asset.

```
  CKEDITOR.plugins.addExternal('lineheight', '/ckeditor-mathtype/plugins/lineheight/', 'plugin.js')
```

**Comment by MoonS11** [comment]
After adding the line height plugin, what if the line height is 1 or too large
