### ISSUE TITLE
Docs & samples

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor4-react#3]
Below is a checklist for docs & samples:

* Samples should be moved entirely to SDK

## React samples (categories)

* Editor types
* Config & listeners (this example should include a custom config, changing the toolbar and a section that logs some events)
* live feed

## Samples styling

* Samples should be styled nicely.

## Docs

* Adjusting editor version / preset, using inline/classic.
* Config customization.
* Listening to events.
* Data binding (pretty much based on live feed).

## Readme

* Image
* Simple code sample
* Link to the docs / sdk

**Comment by Comandeer** [comment]
Docs are already live.
