### ISSUE TITLE
CKEditor created but Toolbar options not visible

### ISSUE THREAD

**Issue by anomepani** [ckeditor/ckeditor4-react#30]
I have installed and configured CKEdito in My React APP as below.
```
import CKEditor from 'ckeditor4-react';

 <CKEditor   data="<p>Editor content</p>"   type="Classic"  />
```

and It looks below as per screenshot.
![image_2019_04_10T13_34_22_526Z](https://user-images.githubusercontent.com/2988295/55883861-b03cc100-5bc4-11e9-826d-7f478752b606.png)

Here I have also tried **type="inline"** Mode but Toolbar option not visible.
However Shortt cut Like` Ctrl+C , Ctrl+B` etc are applied only toolbar not visisble
Am I Missing any configuration of CSS ?

Thanks In Advance.

**Comment by f1ames** [comment]
Hello @anomepani,
have you checked if your usage is similar to what's described in the [official integration docs](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_react.html#basic-usage)? Are there any errors in browser dev console (and which browser you use)?

**Comment by anomepani** [comment]
@f1ames Thanks for the reply. I have found the root cause. Due to some CSS, the toolbar is hidden.

**Comment by Kumudhavalli** [comment]
Hi,
I have the same issue too. whats the css fix that you did?

**Comment by Kumudhavalli** [comment]
just in case somebody is looking for the fix.

override the css class.

.cke .cke_top
{
  display:block !important;
}
