### ISSUE TITLE
ckeditor4-react is not working with next js

### ISSUE THREAD

**Issue by Rahulk4128** [ckeditor/ckeditor4-react#301]
It is working in my react application but now we are migrating to next js and found that CKEditor is not getting rendered in dom or it is not working in next js.

**Comment by Rahulk4128** [comment]
I have changed the version it is working fine. now. can you help how to set the initial value? sometimes the value is set but sometime intiData is not loaded.

**Comment by KarolDawidziuk** [comment]
Hi @Rahulk4128 

> can you help how to set the initial value? 

To set the initial value you can use the [`initData` property](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_react_current.html#data-initialization).

In addition, it seems you have missed our [templates for feature requests and bug reports](https://github.com/ckeditor/ckeditor4/issues/new/choose). Their purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
