### ISSUE TITLE
Throws an error regarding version is not secure

### ISSUE THREAD

**Issue by connectaryal** [ckeditor/ckeditor4-react#304]
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)
Currently, I am using CKEditor in my React app. To integrate into the react application I use ckeditor4-react of version 4.1.2. It was working completely fine but today the editor shows an error "This CKEditor 4.22.1 (Standard) version is not secure. Consider upgrading to the latest one, 4.24.0-lts.".

### Expected result
I do not want to upgrade the version and I just want to remove the error. How can I remove it?

*What is the expected result of the above steps?*

* Integration version:
* CKEditor version: 4
* Installed CKEditor plugins: 
"ckeditor4-react": "^4.1.2",

**Comment by Willian-Fernandes-Andela** [comment]
@connectaryal, have you found a solution for this?

**Comment by jharte-srcinc** [comment]
add versionCheck: false to your config.

https://[ckeditor.com/blog/important-update-for-ckeditor-4-users/](https://ckeditor.com/blog/important-update-for-ckeditor-4-users/)

**Comment by jacekbogdanski** [comment]
Starting July 1st, we activated security notifications for CKEditor 4. You can learn why that step was required from our blogpost: https://ckeditor.com/blog/important-update-for-ckeditor-4-users/

**If you change the versionCheck to false that doesn’t mean you are using a secure CKEditor 4.**

If you are interested in more details about CKEditor 4 LTS (secure version of the editor), [please contact us directly](https://ckeditor.com/contact-sales).

**Comment by jharte-srcinc** [comment]
> 
> **If you change the versionCheck to false that doesn’t mean you are using a secure CKEditor 4.**

Understood.

**Comment by connectaryal** [comment]
> @connectaryal, have you found a solution for this?

I could not figure out the solution yet but Now it only shows for random users but not all users.

**Comment by armenio2** [comment]
![image](https://github.com/ckeditor/ckeditor4-react/assets/25295542/bd093005-299c-4196-9d9a-379927147f56)
add version false in the end of the configuration.

**Comment by connectaryal** [comment]
> ![image](https://private-user-images.githubusercontent.com/25295542/345399475-bd093005-299c-4196-9d9a-379927147f56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjQ4MTEsIm5iZiI6MTcyMTEyNDUxMSwicGF0aCI6Ii8yNTI5NTU0Mi8zNDUzOTk0NzUtYmQwOTMwMDUtMjk5Yy00MTk2LTlkOWEtMzc5OTI3MTQ3ZjU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDEwMDgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExZjc2OTE4YjVmYjYzNzg4ODEwNTkxYzA0YWQzYzIwYTBlMjU1ZDBhZjI3NTJkZjc1MGNhMDQ5ODA0OTM4MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gur4El1bML4pG6GNDPYLBfnoLXNCjQMynaI0jgfigKo) add version false in the end of the configuration.

Problem solved! Thank you so much. @armenio2
