### ISSUE TITLE
Editor issue

### ISSUE THREAD

**Issue by sagarbvora** [ckeditor/ckeditor4-react#307]
I'm using this version "ckeditor4-react": "^2.1.1", but still getting belove error
This CKEditor 4.17.2 version is not secure. Consider [upgrading to the latest one](https://ckeditor.com/ckeditor-4-support/), 4.24.0-lts.

**Comment by jacekbogdanski** [comment]
@sagarbvora please take a look at this discussion: https://github.com/ckeditor/ckeditor4-react/issues/304

**Comment by sagarbvora** [comment]
@jacekbogdanski It means ckeditor4-react not working using ckeditor5 right or wrong?.
