### ISSUE TITLE
How can I use a skin, or just set custom icons?

### ISSUE THREAD

**Issue by ohtanya** [ckeditor/ckeditor4-react#31]
I tried
`<CKEditor
      data="<p>This is an example CKEditor 4 instance.</p>"
      config={{ skin: 'Prestige' }}
/>`
to set a specific skin, because it has lighter icons but it didn't work.

How can I set a specific skin?
Or how can I specify a different file for my icons, since these are too dark for my theme: https://cdn.ckeditor.com/4.11.1/standard-all/skins/moono-lisa/icons.png

**Comment by f1ames** [comment]
The `standard-all` build from CDN supports three official skins by default `moono-lisa`, `moono` and `kama`. These should work with the above config.

However, 3rd-party skins are not included by default, so you should use custom build. The easiest way is to use [online builder](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_skins.html#online-builder-installation) and then use your [customized build in the integration](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_react.html#customizing-ckeditor-preset-or-version).
