### ISSUE TITLE
How do i set the link for CKEditor.editorUrl?

### ISSUE THREAD

**Issue by adigiz** [ckeditor/ckeditor4-react#40]
Hi, i've been searching everywhere but i couldn't seem to find it.

So i saw this post 
[https://github.com/ckeditor/ckeditor4-react/issues/14](url)

I'm using react and it says that i need some kind of relative path. Can anyone one give me an example of that, and how can i achieve it? Thank you

**Comment by f1ames** [comment]
Hi @adigiz,
please take a look on [documentation about customizing CKEditor preset/version](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_react.html#customizing-ckeditor-preset-or-version).

**Comment by adigiz** [comment]
Thanks for replying @f1ames,
I've read the documentation and i still can't seem to make it work.

I've implemented CKEditor 5 before, but it doesn't have the the table resizing capability (Change width of column) and i really need that feature. I decided to change to CKEditor4. But the problem is that the project that  i worked on doesn't allow the use of CDN.

I tried to access it in from node_modules like this
`CKEditor.editorUrl = '../../node_modules/ckeditor4-react/dist/ckeditor.js'`

But it couldn't find the file. I'm kinda new to react so i'm not really sure how to access node_modules like that. Can anyone suggest on how to make it work? Thank you

**Comment by lukasluecke** [comment]
You will have to expose the JS file on your server so it can be accessed from the client (browser).

**Comment by adigiz** [comment]
Thank you @lukasluecke i manage to get it working. So right now i put it in public directory, and it looks really ugly. Can those file be moved to node_modules or src/assets ?

**Comment by f1ames** [comment]
@adigiz You can move entire `ckeditor` folder to any directory in you application, but it has to be exposed by the server so can be loaded by the integration.

The alternative way is to load CKEditor files without the use of integration (your prefered way) and then integration will use `CKEDITOR` namespace if it detects it's available.

**Comment by f1ames** [comment]
Closing as resolved.

**Comment by websal** [comment]
you have to do it in the component

   <CKEditor
                   editorUrl={'URL HERE'}
                   onChange={(event:any) => {
                    const data = event.editor.getData();
                    SetContent(data);
                  }}
                   initData={content}
                  />
