### ISSUE TITLE
Separate `package.json` for dev and build package version

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4-react#42]
Since build package which is released on NPM is a build component version it doesn't need dev dependencies (they are no need in production env AFAIR).

This means the build version should have different `package.json` file (with only `deps` and `peerDeps`).
Also providing different `package.json` means we should provide different and much shorter licensing file (which may be important for some using the package with stricter licensing rules).

**Comment by Comandeer** [comment]
TBH I don't see any sense in preparing another version of `package.json`. Most of the packages uses the same `package.json` in dev and production.

OTOH license file can be simplified.

**Comment by f1ames** [comment]
> OTOH license file can be simplified.

That's the main point here, to simplify licensing. We could just copy `package.json` file on build and remove its `devDependencies` section. WDYT?
