### ISSUE TITLE
Error thrown when quickly changing routes

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor4-react#44]
## Are you reporting a feature request or a bug?

Feature (workaround for upstream bug).

## Provide detailed reproduction steps (if any)

1. Open sample: https://ckeditor.com/docs/ckeditor4/latest/examples/react.html#/
2. Open dev console.
3. Start quickly changing routes (randomly click on buttons under "Click the tab below to change an example.").

### Expected result

No errors in console.

### Actual result

Errors in console

![Screenshot 2019-05-20 at 13 05 54](https://user-images.githubusercontent.com/23366849/58017374-5c48c480-7b00-11e9-919f-032882ca68c9.png)

## Other details

This is related to issues that we have with Angular and Vue integrations. Happens when component is unmounted before editor is fully initialized.

* Browser: …
* OS: …
* Integration version: 1.0.0-beta
* CKEditor version: 4.11.4
* Installed CKEditor plugins: …

**Comment by engineering-this** [comment]
Technically this is an upstream to CKEditor 4. However it can be fixed on Integration side, so this ticket is a feature request for workaround. We will try to fix the editor if we success this can be closed.

**Comment by f1ames** [comment]
Probably related - #35, #49.

**Comment by f1ames** [comment]
Fixed in https://github.com/ckeditor/ckeditor4-react/commit/7b34d2c4f896ced08e66359faca28194ed7e8ef4 via https://github.com/ckeditor/ckeditor4/pull/3128.

**Comment by LeonardoDaLuz** [comment]
This bug returned in version 5. 
![image](https://user-images.githubusercontent.com/80224694/121539313-f3309400-c9db-11eb-8c20-dafed6645074.png)

Steps to reproduce: change the component key to re-mount the component, the error will occours.
