### ISSUE TITLE
Does this support latex?

### ISSUE THREAD

**Issue by mohdsafadsaal** [ckeditor/ckeditor4-react#51]
## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* Integration version: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by Comandeer** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.

**Comment by wwalc** [comment]
Are you looking for https://ckeditor.com/docs/ckeditor4/latest/examples/mathjax.html ?

**Comment by mohdsafadsaal** [comment]
@wwalc Thank you so much, Does this support mathquill ?

**Comment by wwalc** [comment]
No, just pure raw TeX markup is expected in the dialog window for entering formulas. There are alternatives, like MathType for CKEditor 4 if you need an advanced editor with UI for entering formulas: http://www.wiris.com/plugins/demo/ckeditor4/php/
