### ISSUE TITLE
How to disable element in inline editor

### ISSUE THREAD

**Issue by codeporan** [ckeditor/ckeditor4-react#52]
Here is my code , I actually want . user can only read  `<h1>` tag inside inline editor and they can edit only p tag is here . if I use readonly={true} , user can not edit whole data .However,  I want to give permission to user for specific data editing . How can i do this ? 

```js
class EmailEditorApp extends Component {
  constructor(props) {
    super(props);

    this.state = {
      data: '<div><h1>Inline Editing in Action!</h1><p>Inline2 Editing in Action!</p></div>'
    };

    this.handleChange = this.handleChange.bind(this);
    this.onEditorChange = this.onEditorChange.bind(this);
  }

  onEditorChange(evt) {

    this.setState({
      data: evt.editor.getData(),
    });
  }


  handleChange(changeEvent) {
    this.setState({
      data: changeEvent.target.value,
    });
  }
 onSubmit = (e) => {
    e.preventDefault();
    this.setState({
      data: this.state.data,
    })
    console.log(this.state.data)
  }

  render() {   return <HubContent title="User Mail">

      <div>

        <div style={{ overflow: 'auto' }}>
          <CKEditor
            type="inline"
            readOnly={true}
            data={this.state.data}
            onChange={this.onEditorChange}

          />
 
          <button onClick={this.onSubmit}>add</button>
        </div>
      </div>
    </HubContent>
  }
}
export default EmailEditorApp
```

**Comment by f1ames** [comment]
Hi @codeporan,
do you mean that user should be able to edit only part of CKEditor content (only `<p>` and not `<h1>`)? If so there is currently no build in mechanism for that.

You may take a different approach creating multiple inline editor instances only for editable parts of your template and leave the rest as plain HTML. Take a look on docs on [inline editing](https://ckeditor.com/docs/ckeditor4/latest/examples/inline.html).

**Comment by codeporan** [comment]
Thanks for add issues lists , but I have solved problem another ways . 

class EmailEditorApp extends Component {
  state = {
    data:"<!DOCTYPE html> <html> <head> <title>Page Title</title> </head> <body>  <div><div id='header'><p>Header</p></div><div id='content'><p>content is here </p></div><div id='footer'>Footer</div></div> </body> </html>"
  }
  render() {

const doc = new DOMParser().parseFromString(this.state.data, "application/xml");
      const content = doc.getElementById("content").innerHTML
      const header = doc.getElementById("header").innerHTML
      const footer = doc.getElementById("footer").innerHTML

    return <div>

      <Test1 content={content} header={header} footer={footer}/>
    </div>
  }
}
export default EmailEditorApp

import CKEditor from 'ckeditor4-react';
import parse from 'html-react-parser';
class Test1 extends Component {
    state = {
      data:this.props.content,
      header:this.props.header,
      footer:this.props.footer
    }
 
    onEditorChange=(evt) =>{
        this.setState({
          data: evt.editor.getData(),
        });
      }
 

      handleChange = (changeEvent)=> {
        this.setState({
          data: changeEvent.target.value,
        });
      }
    
      onSubmit = (e) => {
        e.preventDefault();
        this.setState({
          data: this.state.data,
        })
        console.log("submit",this.state.data)
      }

    render() {
      return(<div><div style={{ overflow: 'auto' }}>
        <div>{parse(this.state.header)}</div>
      <CKEditor
        type="inline"
        data={this.state.data}
        onChange={this.onEditorChange}
      />
          <div>{parse(this.state.footer)}</div>
    
      <button onClick={this.onSubmit}>add</button>
    </div></div>)
    }
  }
  
  
  export default Test1
