### ISSUE TITLE
Sharedspaces on different components?

### ISSUE THREAD

**Issue by rubenavrebelo** [ckeditor/ckeditor4-react#53]
Hi,

I'm trying to use shared spaces w/react in the following way:
My CKEditor component is wrapped inside a component which handles all the text changes, and, this wrapper component is rendered by a parent component (lets call it CKEditorRenderer), which has multiple childs.

I'm using the sharedspace plugin to change the container of the toolbar so that it appears separated from the editor itself. But, I'd like the div container to be in another component (not CKEditorRenderer nor the wrapper) and have the toolbar render there. I've tried attributing the id to another container but the toolbar reverts to its original state.

I'm not quite sure if that's possible given how the plugin works but any help would be wonderful.

**Comment by f1ames** [comment]
@Comandeer could you take a look on this one?

**Comment by rubenavrebelo** [comment]
Hi,

Seems like I was already able to render the toolbar in another separate component. Something that I realized was that when doing this, the CKEditor component still renders, and, I have to hide it with CSS. It would be nice if the default behavior for sharedspaces was hiding the component.

**Comment by f1ames** [comment]
Hi @rubenavrebelo,
thanks for update, we will have to take a closer look on this one. Can you share your code (just the minimum) which you are using to create sharedspaced editor so we can also check your use case?

**Comment by Dumluregn** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
