### ISSUE TITLE
How to use CKEditor without CDN is not clear

### ISSUE THREAD

**Issue by gsrx** [ckeditor/ckeditor4-react#59]
## Are you reporting a feature request or a bug?
Task

## Provide detailed reproduction steps (if any)
https://ckeditor.com/docs/ckeditor4/latest/guide/dev_react.html

_"Alternatively, you can load CKEditor before loading the CKEditor 4 React component. In this case the component will use the already loaded CKEditor:"_
```
<script src="custom-ckeditor.js"></script>
<script src="node_modules/react/react.production.min.js"></script>
<script src="node_modules/react-dom/react-dom.production.min.js"></script>
<script src="node_modules/ckeditor4-react/dist/ckeditor.js"></script>
<script src="app.js"></script>
```

Its not clear how this works, or what custom-ckeditor.js does. How is the CKEditor.editorUrl overridden?. Please provide a working sample of this type of configuration.

**Comment by Comandeer** [comment]
It's not overridden, as it is used only when component is loaded before CKEditor 4. When CKEditor 4 is loaded before the component, the component uses the globally exposed `CKEDITOR` namespace.

`custom-ckeditor.js` is any build of CKEditor 4, downloaded from [official download site](https://ckeditor.com/ckeditor-4/download/).

**Comment by Aakash-sanandiya** [comment]
I have query on this. I want to use basic CKEditor 4 and now add some plugins to it. I have new ckeditor.js file with added file which I want to keep in my project. Now I want to know how to use that file ? I am using create-react-app.

**Comment by gsrx** [comment]
Add the ckeditor files to your public directory and then add a script tag to the head of index.html
`<script src='%PUBLIC_URL%/ckeditor/ckeditor.js' type='text/javascript' charset='UTF-8'></script>`
