### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by gezquinndesign** [ckeditor/ckeditor4-react#66]
I have multiple instances of the component on one form.  How do I reference a particular instance without adding the CKEDITOR.js script in my index.html?  Is there any way of changing the name of the instance to the id?

Thanks in advance.

**Comment by f1ames** [comment]
Hello @gezquinndesign,
I'm not sure what is your use case exactly, but some time ago we had a ticket which exposes `CKEDITOR` namespace (see #47). With access to `CKEDITOR` namespace, you can use `CKEDITOR.instances.instanceName` to access any instance of CKEditor.

You may also listen to some of instances events to make sure the instance is already initiated (see https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html#event-instanceCreated).

Does it covers your case or you had different usage in mind?

**Comment by gezquinndesign** [comment]
You have to use onBeforeLoad to expose the CKEDITOR namespace.  I'm wondering how to target the created instances so that I can reference them as fields on a form.  Usually I do this by following the technique outlined [here](https://reactjs.org/docs/forms.html#handling-multiple-inputs).  However, if I'm using CKEditor as an input, I'm unsure how I can access the value in a particular instance.

**Comment by Comandeer** [comment]
Sorry for the delayed response!

> Is there any way of changing the name of the instance to the id?

Can you provide more details what do you mean by "id"? As the element to which CKEditor 4 is generated dynamically, it does not have any `[id]` attribute. Probably we'd have to generate some random one.

**Comment by Dumluregn** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
