### ISSUE TITLE
How can I style the editor itself? Can't find any propper documentation.

### ISSUE THREAD

**Issue by ladislavbili** [ckeditor/ckeditor4-react#68]
Simple question, how can I please set style for the editor itself? I know its accepts style property that has to contain css such as: `style={{borderBottom: "0px"}}`
but I cant find any proper documentation how to influence parts of the editor. Currently Im trying to remove background color of the footer (where resize is) and border between it and the editor so it would be seemingly unified. Solution I found online is to just remove the resize button which I dont want to do.
Current one:
![current](https://user-images.githubusercontent.com/27958554/68227317-c3e1c600-fff3-11e9-8aba-4cb629e2146c.PNG)

Wanted result:
![result](https://user-images.githubusercontent.com/27958554/68227319-c3e1c600-fff3-11e9-9365-39ea5c903d88.png)

If I could change default line spacing would be nice too if thats possible.

I tried to view the documentation on the webpage but couldn't find a proper full documentation. Thank you for your answers in advance.

**Comment by f1ames** [comment]
For styling editor content please refer to [`addCss` method](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html#method-addCss).

When it comes to styling UI you can check [different themes](https://ckeditor.com/cke4/addons/skins/all?sort_by=field_custom_downloads_value&sort_order=DESC&page=0), [skin coloring](https://ckeditor.com/docs/ckeditor4/latest/examples/uicolorpicker.html) (and [`config.uiColor`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-uiColor)) or [official tutorial on creating a custom skin](https://ckeditor.com/docs/ckeditor4/latest/guide/skin_sdk_setup.html).

And to remove bottom toolbar part you need to remove `Elements Path` and `Resize` plugins like:

```js
removePlugins: 'elementspath,resize'
```
but then resize would not be available. If you need to keep it you need to add custom CSS which will change its styling.
