### ISSUE TITLE
Dynamic paste html div tag is changed to p tag in editor

### ISSUE THREAD

**Issue by sowmiyaseshadriii** [ckeditor/ckeditor4-react#70]
Hi,

Thanks for the package,
I would like to know how to display the html as such using CKEditor 4 reactjs. It displays the editor but the inline style are removed and all div tag changed to P tag.

How to display the html as it is without changing div to P tag
```
import React from "react";
import CKEditor from 'ckeditor4-react';


class Editor extends React.PureComponent{

    constructor(props) {
    super(props);
    this.state = {
      config: {
        extraAllowedContent: 'div(*)',
        allowedContent: true
      }
     emailbody: `
        <!DOCTYPE html>
        <html lang="en">
        <head>
        <title></title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        </head>
        <body  style="background-color: #DAD5CE; font-family:'browntt-regular', Verdana, Geneva, Tahoma, sans-serif">
         <div class="content-box" style="display: block; align-items: center; justify-content: center; margin:25px 0">
                    <div style="height:100%; text-align: center;display:block; ">
                        <div style="font-weight: normal; font-size: 24pt; color: #000">order confirmation</div>
                        <div class="orderdate" style="font-size: 12pt; color: #51545D">order date:
                             <span style="color: #B39137;">${orderdate!''} </span>
                        </div>
                    </div>
                </div>
        </body>
        </html>`
    }

handleChange = value => {
 this.setState({ emailbody: value });
}
    render(){
       <div>
         <CKEditor
              data={this.state.emailbody}
              onChange={this.handleChange}
              config={this.config}
          />
          </div>
    }

}

```

**Comment by jacekbogdanski** [comment]
This is not a strict React integration issue but default CKEditor4 behavior. By default, any new line key will be treated as a new paragraph, so when you are modifying your HTML with default settings, some of the div may be replaced by paragraphs and newly created lines will be encoded as `p` tags. To change the default behavior, please set `config.enterMode` configuration option to [CKEDITOR.ENTER_DIV](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#property-enterMode).

Also, as you would like to edit content as a whole HTML page, I recommend setting [config.fullPage](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-fullPage) option, so you don't need to use insecure `allowedContent: true`. You may also want to take a look at [Document Properties](https://ckeditor.com/cke4/addon/docprops) plugin which should provide a better experience with editing full HTML pages.
