### ISSUE TITLE
core-js dependency is deprecated - cannot build package

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor4-react#72]
## Provide detailed reproduction steps (if any)

1. Clone repo or remove all `node_modules`
2. Install dependencies
3. Try to build package

### Expected result

It is possible to build package without the errors.

### Actual result

`core-js` dpeendency is not installed properly, what cause error during package building

## Other details

```sh
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

> fsevents@1.2.11 install /Users/msamsel/work/ckeditor4-react/node_modules/watchpack/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> core-js@2.6.11 postinstall /Users/msamsel/work/ckeditor4-react/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
```

* Browser: …
* OS: …
* Integration version: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by mehta0414** [comment]
I am getting same error after installing TestCafe

**Comment by DanielLoyAugmedix** [comment]
I am seeing the same issue after executing the simple
```
ng new my-app
```

**Comment by Mandipluitel** [comment]
use of sudo solved the issue in mine

**Comment by ganeshkhatmode** [comment]
@msamsel 
[gajnakjnckejnk](http://localhost:8081)
**Ganesh Patil**

**Comment by f1ames** [comment]
Another issue related to \`core-js\` - #76.

**Comment by bekagaw653** [comment]
already solved at https://icetutor.com/question/npm-warn-deprecated-core-js2-6-11-core-js3-is-no-longer-maintained-and-not-recommended-for-usage-due-to-the-number-of-issues/
