### ISSUE TITLE
Add sample to the integration

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor4-react#73]
## Are you reporting a feature request or a bug?

feature

## Provide detailed reproduction steps (if any)

There is no easy out of the box working application which will include all modification introduced in the repository. It could be nice to have such a place for fast mockups and tests.

## Other details

* Browser: …
* OS: …
* Integration version: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
DUP of #54.
