### ISSUE TITLE
String Prototype pollution - startsWith

### ISSUE THREAD

**Issue by SamKirkland** [ckeditor/ckeditor4-react#76]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Try to add CKEditor on a Webforms page with MicrosoftAjax (default webforms js)
2.  You'll get a compatibility error due to MicrosoftAjax attempting to add a polyfill for startsWith. This is an issues because CKEditor adds another pollyfill later that calls into microsofts pollyfill.
3. The main issues that causes this is microsofts polyfill doesn't support a second argument (the position argument). And CKEditors polyfill defaults this argument to 0

### Expected result

If CKEditor see's the property String.Prototype.startsWith is already defined it should not redefine it. This is a good idea anyway. If the spec changes (ex: a third argument is added) no code will need to change on CKEditors side, Also the native C browser implementation will be used on modern browsers for a speed boost instead of always using the javascript pollyfill.

This is actually a bug on both CKEditors side and microsofts side, both should be checking before adding polyfills. The bug will be fixed if either library implements a check. I will be submitting a ticket to the webforms team as well.

### Actual result

CKEditor always redefines startsWith and defaults the second argument to 0

## Other details

* Browser: Any (Tested on latest FF, latest Chrome, IE11)
* OS: Any (Tested on windows 10)
* CKEditor version: CKEditor version 4.13.1 included via CKEDitor4-react latest (v1.0.1)
* Installed CKEditor plugins: Spell checker

**Comment by jacekbogdanski** [comment]
I moved the issue into React integration repository as we are not using `startsWith` polyfill in CKEditor codebase, but indeed such polyfill should be added during building process by Webpack and babeljs compiler for React integration.

I can confirm that polyfill is added on browsers missing it (like IE11), however, it seems to always check if `startsWith` doesn't exist and tries to use native one if possible. To verify it I just overwrote `String.prototype.startsWith` before loaded react built script.

Could you provide some demo with minimal CKEditor4 react integration configuration confirming the issue? I mean demo without MicrosoftAjax or any other 3rd party framework which may cause the issue by themself, so we can clearly see it's CKEditor4 React integration bug?

**Comment by SamKirkland** [comment]
@jacekbogdanski thanks, I've put together an [example](https://codesandbox.io/s/ckeditor-4-react-prototype-pollution-wkvol)
I've copied the ckeditor4-react dist file into the codeSandbox and modified the following sections to help with debugging.

At the top (line 1) of `ckeditor.dist.js` I added a startsWith polyfill
```javascript
// If ckeditor sees startsWith has been redefined it will also redefine it
// I've added this pollyfill as an example
Object.defineProperty(String.prototype, 'startsWith', {
  value: function(search, rawPos) {
      var pos = rawPos > 0 ? rawPos|0 : 0;
      return this.substring(pos, pos + search.length) === search;
  }
});
```
On line 1579 of `ckeditor.dist.js` I added a console.log() line so we can detect whenever CKEDITORS pollyfill is used. Note this is called whenever the polyfill is being used, not on initial add
```javascript
console.log("CKEditor redefined startsWith");
```
Opening the console you can see multiple log instances of "CKEditor redefined startsWith"

```javascript
r({
    target: "String", // lets modify the string prototype
    proto: !0, // true... thanks js minifier
    forced: !u("startsWith") // looks like !u("startsWIth") is detecting when a prototype exists already and if force overwriting it
}, /* startswith polyfill... */)
```

**Comment by Comandeer** [comment]
This is in fact upstream issue in [`core-js`](https://github.com/zloirock/core-js), which we use to include polyfills for older browsers. It seems that `core-js` does some checks if the polyfill works in the correct, defined in the standard way.

I've updated `core-js` version to the latest version in #80 – you can try to build the component using that branch. The check before adding the polyfill is different, so maybe it would resolve your issue. If not, please fill the issue directly in [`core-js` repository](https://github.com/zloirock/core-js).
