### ISSUE TITLE
react ckeditor 4 doesnt display the font family and fontsize in toolbar

### ISSUE THREAD

**Issue by Kumudhavalli** [ckeditor/ckeditor4-react#81]
## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* Integration version: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by Comandeer** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests](https://github.com/ckeditor/ckeditor4-react/blob/master/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.
