### ISSUE TITLE
Data not showing in editor

### ISSUE THREAD

**Issue by coderbhaai** [ckeditor/ckeditor4-react#87]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
I am binding the editor with functions and they wrok well on uploading of data 
onEditorChange1( evt1 ) { this.setState( { short_desc: evt1.editor.getData() } ) }
handleChange2( changeEvent2 ) { this.setState( { long_desc: changeEvent2.target.value } ) }

componentDidMount(){
        const url= this.props.match.params.url
        axios.get('/api/v1/XXXXXXX/' + url)
        .then(response =>{
            this.setState({
                short_desc:                         response.data.datax[0].short_desc,
            })
        })
        window.scrollTo(0, 0)
    }
this.state.sshort_desc is appearing in console but not in editor

<CKEditor onBeforeLoad={ ( CKEDITOR ) => ( CKEDITOR.disableAutoInline = true ) } data={this.state.short_desc} short_desc={this.state.short_desc} onChange={this.onEditorChange1}/>

### Expected result

Data should show in editor like it does in CKEditor 5

### Actual result

Blank screen is coming

## Other details

* Installed CKEditor plugins: …
None

**Comment by jacekbogdanski** [comment]
I created simple demo nicely handling async components, see https://codepen.io/jacekbogdanski/pen/qBdxazo?editors=1010

Everything seems to work when using an async data update. Could you extend this demo (as a fork) with the issue?

**Comment by coderbhaai** [comment]
@jacekbogdanski 

Thanks for the help.
Guess something was wrong and it sorted by itself. I don't know how but its working now.

Appreciated.
Thanks

**Comment by jacekbogdanski** [comment]
Good to hear :+1:

**Comment by Somethingbear** [comment]
> Good to hear 👍

line9
setTimeout( resolve, 1000 ); -> resolve(); 
then it doesn't work.

**Comment by kushalthakur** [comment]
How is issue resolved I'm using CKEditor5 and I'm facing same problem you put the static value like : this.setState( { desc: 'Updated desc.'} );
My code :
componentDidMount() {
      if (this.props.storypageOne !== '') {
         if (this.props.formType === "edit") {
            const { page_content } = this.props.storypageOne
            this.setState({ page_content })
         }
      } else {
         if (this.props.formType === "edit") {
            const { page_content } = this.props.data
            this.setState({ page_content })
         }
      }
   }
<CKEditor
                     editor={ClassicEditor}
                     data={this.state.page_content === null ? '' : this.state.page_content}
                     // data="<p><strong>this is a file</strong></p>"
                     onChange={this.ckEditorHandleChange}
                  />
                  {this.state.page_content === null ? '' : this.state.page_content}
is appearing in the outside ckeditor but not in editor data attr and when I use static data value then show me on editor

**Comment by kushalthakur** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/47447927/87215991-03b63580-c359-11ea-8d2a-8e703ee613f0.png)

**Comment by f1ames** [comment]
@kushalthakur if you have any issues with CKEditor 5 integration, please report an issue in https://github.com/ckeditor/ckeditor5-angular. This is CKEditor 4 Angular integration repository.

**Comment by kushalthakur** [comment]
@f1ames Thanks for your response, but it's working for me after 4-5 day R&N

**Comment by sohailhaider** [comment]
> I created simple demo nicely handling async components, see https://codepen.io/jacekbogdanski/pen/qBdxazo?editors=1010
> 
> Everything seems to work when using an async data update. Could you extend this demo (as a fork) with the issue?

On this demo even description stays "Old desc.", how to change it to upated?

**Comment by mohamedshahid** [comment]
Hi all I got a new solution create another state showEditor with default false and in setTimeout upate it to true and while returning use code as below
{
 this.state.showEditor &&
 <CKEditor data={this.state.desc} />
}
