### ISSUE TITLE
Icon is deleted even with allowedContent or extraAllowedContent

### ISSUE THREAD

**Issue by Fluorz** [ckeditor/ckeditor4-react#93]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Paste icon in source
2. Go back in normal view
3. Icon is deleted

### Expected result

The icon have to stay in source

### Actual result

The icon is deleted

## Other details

* Browser: Chrome
* OS: OSX
* CKEditor version: 1.10

I did this : 

`<CKEditor data="<p>hello</p>" config={{extraAllowedContent: 'i', allowedContent: true}} onChange={this.onChange}/>
`

Thank you

**Comment by Dumluregn** [comment]
Hello, could you provide the code you paste to the editor?

**Comment by Fluorz** [comment]
Hello, i have tried with fontawesome

`<i class="fas fa-spray-can"></i>`

**Comment by Dumluregn** [comment]
CKEditor 4 removes empty elements to keep HTML clean. Please see this SO answer on how to keep empty elements in the editor - [https://stackoverflow.com/a/21118988/646871](https://stackoverflow.com/a/21118988/646871).

**Comment by Fluorz** [comment]
I still don't have fixe this issue. 

My code is : 

`<CKEditor data={this.state.text} 
                    config={{extraAllowedContent: 'p(*)[*]{*};div(*)[*]{*};li(*)[*]{*};ul(*)[*]{*};i(*)[*]{*}', 
                                    allowedContent: true, protectedSource : [/<i[^>]*><\/i>/g],
                                    removeEmpty: {i : false} }}                                    
                    onChange={this.onChange}/>
`

In the StackOverflow solution they also used : 

`CKEDITOR.dtd.$removeEmpty['i'] = false;`

But how I can use and implement this in React ?

The HTML code that I'm trying to paste and save is simply a fontawaseome icon : 

`<i class="fas fa-home"></i>`

**Comment by Dumluregn** [comment]
Hello again.
`removeEmpty` is not a valid [CKEditor 4 configuration option](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html), so allowing the `i` element to be empty this way won't work. As for the `CKEDITOR.dtd.$removeEmpty['i'] = false;` way, to use it in React you can edit the `CKEDITOR` object in the same way as without a framework - you just need to do it after it's loaded, but before component is initialised. We are planning to expose API to facilitate that soon, for now you may check [how it can be done](https://github.com/ckeditor/ckeditor4-integrations-common/blob/master/src/getEditorNamespace.js) as a workaround.
