### ISSUE TITLE
Bug: Null reference when editor instance is destroyed before initialization completed

### ISSUE THREAD

**Issue by Garbanas** [ckeditor/ckeditor4-react#94]
## Description 
In the default settings the required JS for the editor is asynchronously loaded from a CDN.
After the request completes (which may take some time), it is not checked whether the component has already been destroyed in the meantime, resulting in a null reference when trying to access the root element for the editor. 

See https://github.com/ckeditor/ckeditor4-react/pull/91 for a fix.

## Steps to reproduce

1. Ensure no cached data is present
2. Quickly cycle through creating and destroying a ckeditor4-react component
3. The first component should trigger the request but is unable to honour the response

See https://stackblitz.com/edit/react-chw3zb and look at the console output.

### Expected result

No errors.

### Actual result

Errors logged to console:
```
[CKEDITOR] Error code: editor-incorrect-element. {element: null}
[CKEDITOR] For more information about this error go to https://ckeditor.com/docs/ckeditor4/latest/guide/dev_errors.html#editor-incorrect-element
```

**Comment by offaxis** [comment]
I got this error too ! 
Thanks for the correction  @Garbanas !

Will this pull-request be merged soon ?

**Comment by jacekbogdanski** [comment]
Thanks for the nicely written report - indeed it seems like component could be initialized and destroyed before lazy loading resolves editor.

@offaxis hopefully :wink:
