### ISSUE TITLE
CORB error. One of the root or intermediate certificates has expired

### ISSUE THREAD

**Issue by luccabb** [ckeditor/ckeditor4-react#98]
# Expired Certificate

I am receiving this error when I try to open this URL in my Work Environment:

URL: https://cdn.ckeditor.com/4.14.0/standard-all/ckeditor.js

Error: `One of the root or intermediate certificates has expired (5 days ago)`
It also gives me the following info, in case it helps:
`Common Name: cdn.ckeditor.com`
`SANs: cdn.ckeditor.com, www.cdn.ckeditor.com`

CKEditor wasn't loading on my page and Chrome started throwing the following error:

`Cross-Origin Read Blocking (CORB) blocked cross-origin response https://cdn.ckeditor.com/4.14.0/standard-all/ckeditor.js with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.`

Do you have any plans to add a new certificate to the URL?

**Comment by f1ames** [comment]
Hi @luccabb,

thanks for the report. This issue has already been dealt with, our CDN provider should apply the changes soon :crossed\_fingers:
